parameters:
    oro_dashboard.form.type.edit.class: Oro\Bundle\DashboardBundle\Form\Type\DashboardType

services:
    oro_dashboard.form.type.edit:
        class: %oro_dashboard.form.type.edit.class%
        tags:
            - { name: form.type, alias: "oro_dashboard_edit" }
