oro_menu_config:
    items:
        dashboard_tab:
            label: 'oro.dashboard.dashboards_tab_label'
            uri: '#'
            extras:
                position: 10
        daboards_management:
            label: 'oro.dashboard.dashboards_list_menu_label'
            route: 'oro_dashboard_management'
            extras:
                position: 10
                routes: ['oro_dashboard_update', 'oro_dashboard_create']

    tree:
        application_menu:
            children:
                dashboard_tab:
                    children:
                        daboards_management: ~

oro_titles:
    oro_dashboard_index: "%%name%%"
    oro_dashboard_quick_launchpad: oro.dashboard.title.quick_launchpad

    daboards_management: 'Dashboards'
    oro_dashboard_edit: '%%name%% - Edit - Dasboards'
    oro_dashboard_create: 'Create Dashboard'
