oro_menu_config:
    items:
        dashboard_tab:
            label: 'oro.dashboard.dashboards_tab_label'
            uri: '#'
            extras:
                position: 10
        oro_dashboard_index:
            label: 'oro.dashboard.dashboards_list_menu_label'
            route: 'oro_dashboard_index'
            extras:
                position: 10
                routes: ['oro_dashboard_update', 'oro_dashboard_create']

    tree:
        application_menu:
            children:
                dashboard_tab:
                    children:
                        oro_dashboard_index: ~

oro_titles:
    oro_dashboard_index: oro.dashboard.entity_plural_label
    oro_dashboard_quick_launchpad: oro.dashboard.title.quick_launchpad
    oro_dashboard_view: "%%entity.name%%"
    oro_dashboard_open: "%%name%%"

    oro_dashboard_update: '%%name%% - Edit - Dasboards'
    oro_dashboard_create: 'Create Dashboard'
