config:
    map:
        '*':
            'oro/dashboard-item-widget': 'orodashboard/js/widget/dashboard-item'
    paths:
        'orodashboard/js/widget/dashboard-item': 'bundles/orodashboard/js/widget/dashboard-item.js'
