parameters:
    oro_dashboard.manager.class:      Oro\Bundle\DashboardBundle\Manager
    oro_dashboard.configuration.loader.class: Oro\Bundle\DashboardBundle\Configuration\ConfigurationLoader
    oro_dashboard.configuration.manager.class: Oro\Bundle\DashboardBundle\Configuration\ConfigurationManager
    oro_dashboard.widget_model_factory.class:      Oro\Bundle\DashboardBundle\Model\WidgetModelFactory
    oro_dashboard.config_provider.class:     Oro\Bundle\DashboardBundle\Provider\ConfigProvider

services:
    oro_dashboard.manager:
        class: %oro_dashboard.manager.class%
        arguments:
            - @oro_dashboard.config_provider
            - @oro_security.security_facade
            - @doctrine.orm.entity_manager
            - @oro_dashboard.widget_model_factory

    oro_dashboard.configuration.loader:
        class: %oro_dashboard.configuration.loader.class%
        arguments:
            - %kernel.bundles%

    oro_dashboard.configuration.manager:
        class: %oro_dashboard.configuration.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            
    oro_dashboard.widget_model_factory:
        class: %oro_dashboard.widget_model_factory.class%
        arguments:
            - @oro_dashboard.config_provider
            - @oro_security.security_facade
    
    oro_dashboard.config_provider:
        class: %oro_dashboard.config_provider.class%
        arguments:
            - []
