parameters:
    oro_dashboard.config_resolver.class:         Oro\Component\Config\Resolver\SystemAwareResolver
    oro_dashboard.manager.state.class:           Oro\Bundle\DashboardBundle\Model\StateManager
    oro_dashboard.manager.class:                 Oro\Bundle\DashboardBundle\Model\Manager
    oro_dashboard.widget_configs.class:          Oro\Bundle\DashboardBundle\Model\WidgetConfigs
    oro_dashboard.factory.class:                 Oro\Bundle\DashboardBundle\Model\Factory
    oro_dashboard.config_provider.class:         Oro\Bundle\DashboardBundle\Model\ConfigProvider
    oro_dashboard.dashboard_entity.class:        Oro\Bundle\DashboardBundle\Entity\Dashboard
    oro_dashboard.dashboard_widget_entity.class: Oro\Bundle\DashboardBundle\Entity\Widget
    oro_dashboard.navigation_listener.class:     Oro\Bundle\DashboardBundle\EventListener\NavigationListener
    oro_dashboard.form.type.edit.class:          Oro\Bundle\DashboardBundle\Form\Type\DashboardType
    oro_dashboard.form.type.select.class:        Oro\Bundle\DashboardBundle\Form\Type\DashboardSelectType
    oro_dashboard.provider.widget_configuration_form_provider.class:  Oro\Bundle\DashboardBundle\Provider\WidgetConfigurationFormProvider
    oro_dashboard.widget_config_value.provider.class: Oro\Bundle\DashboardBundle\Provider\ConfigValueProvider
    oro_dashboard.widget_config_value.date_range.converter.class: Oro\Bundle\DashboardBundle\Provider\Converters\FilterDateTimeRangeConverter
    oro_dashboard.datetime.hepler.class: Oro\Bundle\DashboardBundle\Helper\DateHelper

services:
    oro_dashboard.config_resolver:
        class: %oro_dashboard.config_resolver.class%
        arguments:
            - @service_container

    oro_dashboard.widget_configs:
        class: %oro_dashboard.widget_configs.class%
        arguments:
            - @oro_dashboard.config_provider
            - @oro_security.security_facade
            - @oro_dashboard.config_resolver
            - @doctrine.orm.entity_manager
            - @oro_dashboard.manager.state
            - @oro_dashboard.widget_config_value.provider
        calls:
            - [setRequest, ["@?request="]]

    oro_dashboard.widget_config_value.provider:
        class: %oro_dashboard.widget_config_value.provider.class%

    oro_dashboard.widget_config_value.date_range.converter:
        class: %oro_dashboard.widget_config_value.date_range.converter.class%
        arguments:
            - @oro_locale.formatter.date_time
            - @oro_filter.expression.date.compiler
        tags:
            - { name: oro_dashboard.value.converter, alias: "oro_type_date_range_filter" }

    oro_dashboard.manager:
        class: %oro_dashboard.manager.class%
        arguments:
            - @oro_dashboard.factory
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper
            - @security.context

    oro_dashboard.factory:
        class: %oro_dashboard.factory.class%
        arguments:
            - @oro_dashboard.config_provider
            - @oro_dashboard.manager.state

    oro_dashboard.manager.state:
        class: %oro_dashboard.manager.state.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.security_facade

    oro_dashboard.config_provider:
        class: %oro_dashboard.config_provider.class%
        arguments:
            - []
            - @event_dispatcher

    oro_dashboard.navigation_listener:
        class: %oro_dashboard.navigation_listener.class%
        arguments:
            - @oro_security.security_facade
            - @oro_dashboard.manager
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }

    oro_dashboard.form.type.edit:
        class: %oro_dashboard.form.type.edit.class%
        tags:
            - { name: form.type, alias: "oro_dashboard" }

    oro_dashboard.form.type.select:
        class: %oro_dashboard.form.type.select.class%
        arguments:
            - @oro_dashboard.manager
        tags:
            - { name: form.type, alias: "oro_dashboard_select" }

    oro_dashboard.provider.widget_configuration_form_provider:
        class: %oro_dashboard.provider.widget_configuration_form_provider.class%
        arguments:
            - @oro_dashboard.config_provider
            - @form.factory
            - @oro_form.validator.constraint_factory

    oro_dashboard.datetime.hepler:
        class: %oro_dashboard.datetime.hepler.class%
        arguments:
            - @oro_locale.formatter.date_time
