oro_dashboard:
    resource:     "@OroDashboardBundle/Controller"
    type:         annotation
    prefix:       /

oro_dashboard_api:
    resource: Oro\Bundle\DashboardBundle\Controller\Api\Rest\WidgetController
    type: rest
    prefix: api/rest/{version}/
    requirements:
        version:  latest|v1
        _format: json
    defaults:
        version: latest
